language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
  - xvfb-run wct
  - bash ./gpages_build.sh citydogweb dogzone-map tobiashutterer tobias.hutterer@gmail.com
before_script:
- npm install -g polylint web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
- polylint
